/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as revenueSplitSol from "./RevenueSplit.sol";
export type { revenueSplitSol };
export type { CollaborationManager } from "./CollaborationManager";
export type { LikeRegistry } from "./LikeRegistry";
export type { LyricsNFT } from "./LyricsNFT";
export type { LyricsRegistry } from "./LyricsRegistry";
export type { VoteContract } from "./VoteContract";
