/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LikeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "isLiked" | "like" | "likeCount" | "liked" | "unlike"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Liked" | "Unliked"): EventFragment;

  encodeFunctionData(
    functionFragment: "isLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "like", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "likeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "liked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlike",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "isLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "like", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likeCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "liked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unlike", data: BytesLike): Result;
}

export namespace LikedEvent {
  export type InputTuple = [songId: BigNumberish, user: AddressLike];
  export type OutputTuple = [songId: bigint, user: string];
  export interface OutputObject {
    songId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlikedEvent {
  export type InputTuple = [songId: BigNumberish, user: AddressLike];
  export type OutputTuple = [songId: bigint, user: string];
  export interface OutputObject {
    songId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LikeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LikeRegistry;
  waitForDeployment(): Promise<this>;

  interface: LikeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isLiked: TypedContractMethod<
    [songId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  like: TypedContractMethod<[songId: BigNumberish], [void], "nonpayable">;

  likeCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  liked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  unlike: TypedContractMethod<[songId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isLiked"
  ): TypedContractMethod<
    [songId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "like"
  ): TypedContractMethod<[songId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "likeCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "liked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "unlike"
  ): TypedContractMethod<[songId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Liked"
  ): TypedContractEvent<
    LikedEvent.InputTuple,
    LikedEvent.OutputTuple,
    LikedEvent.OutputObject
  >;
  getEvent(
    key: "Unliked"
  ): TypedContractEvent<
    UnlikedEvent.InputTuple,
    UnlikedEvent.OutputTuple,
    UnlikedEvent.OutputObject
  >;

  filters: {
    "Liked(uint256,address)": TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;
    Liked: TypedContractEvent<
      LikedEvent.InputTuple,
      LikedEvent.OutputTuple,
      LikedEvent.OutputObject
    >;

    "Unliked(uint256,address)": TypedContractEvent<
      UnlikedEvent.InputTuple,
      UnlikedEvent.OutputTuple,
      UnlikedEvent.OutputObject
    >;
    Unliked: TypedContractEvent<
      UnlikedEvent.InputTuple,
      UnlikedEvent.OutputTuple,
      UnlikedEvent.OutputObject
    >;
  };
}
